server:
  port: 88
spring:
  application:
    name: glume-gateway
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
            - Path=/baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
            - Path=/qq
    nacos:
      discovery:
        server-addr: localhost:8848