server:
  port: 88
spring:
  application:
    name: glume-gateway
  cloud:
    gateway:
      routes:
        # 产品服务路由
        - id: product_route
          uri: lb://glume-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        # 库存服务路由
        - id: glume-ware
          uri: lb://glume-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        # 会员服务路由
        - id: member_router
          uri: lb://glume-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        # 第三方服务路由
        - id: third_party_route
          uri: lb://glume-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        # admin服务路由
        - id: admin_route
          uri: lb://glume-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: glume_host_route
          uri: lb://glume-product
          predicates:
            - Host=glumemall.com,**.glumemall.com
    nacos:
      discovery:
        server-addr: localhost:8848