server:
  port: 20000
spring:
  application:
    name: glume-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  redis:
    database: 0
    host: localhost
    port: 6379