spring:
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.163.com
    # qq邮箱SMTP port 是465, 163邮箱SMTP port 是25
    port: 25
    # 发送者邮箱
    username: tuoyingtao@163.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: AVMTEICLUBQUAVZX
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        stmp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
