server:
  port: 30000
spring:
  application:
    name: glume-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# alibaba oss 对象存储
alibaba:
  cloud:
    oss:
      bucket: glume-mall
