server:
  port: 25000
spring:
  application:
    name: glume-seckill
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  redis:
    host: localhost
    port: 6379
    database: 0
  # 异步任务
  task:
    execution:
      pool:   #线程池
        core-size: 20   # 默认线程
        max-size: 50    # 默认线程
  session:
    store-type: redis
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: / #虚拟主机
    publisher-confirm-type: correlated  # 开启发送端确认
    publisher-returns: true             # 开启发送端消息抵达队列确认
    template:
      mandatory: true # 只要抵达队列，以异步发送优先回调 ReturnConfirm
    listener:
      simple:
        acknowledge-mode: manual # 开启手动确认ACK消息；避免多条消息在宕机的时候丢失；（默认为自动确认回复）
  thymeleaf:
    cache: false
  # 链路追踪
  zipkin:
    base-url: http://192.168.19.130:9411
    discovery-client-enabled: false       # 关闭服务发现，否则Spring Cloud 会把 zipkin 的url当作服务名称
    sender:
      type: web      # 设置传输数据的方式
  sleuth:
    sampler:
      rate: 1        # 设置抽样采集率，默认：0.1，即10%
feign:
  sentinel:
    # 开启熔断保护机制
    enabled: true
# 链路追踪开启debug日志
logging:
  level:
    com.glume.glumemall: debug
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug