server:
  port: 25000
spring:
  application:
    name: glume-seckill
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
    database: 0
  # 异步任务
  task:
    execution:
      pool:   #线程池
        core-size: 20   # 默认线程
        max-size: 50    # 默认线程
