server:
  port: 8000
spring:
  application:
    name: glume-member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/glumemall_ums?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
    database: 0
  #Spring session 配置
  session:
    store-type: redis
    timeout: 30m
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #主键自增
swagger:
  enabled: true
jwt:
  header: "Authorization"
logging:
  level:
    com.glume.glumemall: debug
