server:
  port: 30000
spring:
  application:
    name: glume-cart
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  redis:
    host: localhost
    port: 6379
    database: 0
  session:
    store-type: redis
    timeout: 10m